server:
  port: 8081
spring:
  application:
    name: alibaba-zk-consumer

dubbo:
  application:
    name: alibaba-zk-consumer
  registry:
    address: zookeeper://81.69.255.17:5500
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 20002
  consumer:
    check: false
    timeout: 3000
