dubbo:
  application:
    name: apache-redis--provider
  registry:
    address: 81.69.255.17:5115
#    address: 81.69.255.17:5400,81.69.255.17:5401,81.69.255.17:5402,81.69.255.17:5403,81.69.255.17:5404,81.69.255.17:5405
    protocol: redis
    check: false
    password: redis1234
    username: redis

  protocol:
    name: dubbo
    port: -1
  provider:
    timeout: 3000
  consumer:
    check: false
    timeout: 3000
    loadbalance: roundrobin