server:
  port: 8082
spring:
  application:
    name: apache-redis-consumer

dubbo:
  application:
    name: apache-redis-consumer
  registry:
    address: 81.69.255.17:5115
#    address: 81.69.255.17:5400,81.69.255.17:5401,81.69.255.17:5402,81.69.255.17:5403,81.69.255.17:5404,81.69.255.17:5405
    protocol: redis
    check: false
    password: redis1234
  protocol:
    name: dubbo
    port: 20006
  consumer:
    timeout: 3000
    check: false
