dubbo:
  application:
    name: apache-zk-provider
  registry:
    address: 81.69.255.17:5500
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 20003
  provider:
    timeout: 3000